# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukH6wV7xp8u7N7quRNHYfz4Z0yNxLbCx
"""

import numpy as np
import random

def tanh(x) :
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def der_tanh(x):
  return 1.0 - (tanh(x) ** 2)

def predict(input, W1, W2): 
  Z12 = np.dot(W1, input)
  Z12_ = tanh(Z12)
  Z12_ = np.append(Z12_, 1).reshape(3, 1)
  Z3 = np.dot(W2, Z12_)
  Z3_ = tanh(Z3)
  return Z3_, Z3, Z12_, Z12

def backward(label, input, y_hat, Z3, Z12_, Z12, W2):
  dW2 = -(label - y_hat)*der_tanh(Z3)*Z12_
  input = input.reshape(3)
  dW1 = -(label - y_hat)*der_tanh(Z3)*np.array([[W2[0][0]],[W2[0][1]]])*der_tanh(Z12)*np.stack([input, input])
  return dW1, dW2


b1 = 2.0
b2 = 2.0
b3 = 4.0

#------------Q1--------------
w11 = (b2 + 1)/10.0
w12 = -(b3 + 1)/10.0
w13 = (b1 + 1)/10.0
w14 = (b1 + 1)/10.0
w15 = (b2 + 1)/10.0
w16 = -(b3 + 1)/10.0
w21 = -(b1 + 1)/10.0
w22 = -(b2 + 1)/10.0
w23 = -(b3 + 1)/10.0

W1 = np.array([[w11, w13, w15],[w12 ,w14, w16]])
W2 = np.array([[w21, w22, w23]])

print("Q1 W1\n", W1)
print("Q1 W2\n", W2)


#------------Q2-----------------
input = np.array([[1], [1], [1]]) #input "very good"
label = 1

y_hat, Z3, Z12_, Z12 = predict(input, W1, W2)
print("Q2 y",y_hat)
dW1, dW2 = backward(label, input, y_hat, Z3, Z12_, Z12, W2)
W1 -= dW1
W2 -= dW2.reshape(1, 3)
#print(dW1)
#print(dW2.reshape(1, 3))
print("Q2 W1\n", W1)
print("Q2 W2\n", W2)


#------------Q3-----------------
input = np.array([[0], [1], [1]]) #input "not good"
label = -1

y_hat, Z3, Z12_, Z12 = predict(input, W1, W2)
print("Q3 y",y_hat)
dW1, dW2 = backward(label, input, y_hat, Z3, Z12_, Z12, W2)
W1 -= dW1
W2 -= dW2.reshape(1, 3)
#print(dW1)
#print(dW2.reshape(1, 3))
print("Q3 W1\n", W1)
print("Q3 W2\n", W2)


#------------Q4-----------------
input = np.array([[0], [0], [1]]) #input "not bad"
label = 1

y_hat, Z3, Z12_, Z12 = predict(input, W1, W2)
print("Q4 y",y_hat)
dW1, dW2 = backward(label, input, y_hat, Z3, Z12_, Z12, W2)
W1 -= dW1
W2 -= dW2.reshape(1, 3)
#print(dW1)
#print(dW2.reshape(1, 3))
print("Q4 W1\n", W1)
print("Q4 W2\n", W2)


#------------Q5-----------------
input = np.array([[1], [0], [1]]) #input "very bad"
label = -1

y_hat, Z3, Z12_, Z12 = predict(input, W1, W2)
print("Q5 y",y_hat)
dW1, dW2 = backward(label, input, y_hat, Z3, Z12_, Z12, W2)
W1 -= dW1
W2 -= dW2.reshape(1, 3)
#print(dW1)
#print(dW2.reshape(1, 3))
print("Q5 W1\n", W1)
print("Q5 W2\n", W2)


for i in range(1000):
  rand = random.random()
  if rand < 0.25 :
    input = np.array([[1], [1], [1]]) #input "very good"
    label = 1
  elif rand <0.5 :
    input = np.array([[0], [1], [1]]) #input "not good"
    label = -1
  elif rand < 0.75 :
    input = np.array([[0], [0], [1]]) #input "not bad"
    label = 1
  else :
    input = np.array([[1], [0], [1]]) #input "very bad"
    label = -1
  
  y_hat, Z3, Z12_, Z12 = predict(input, W1, W2)
  if i >900 :
    print("Q" +str(i+6)+ "y", y_hat)
    print("Q" +str(i+6)+ "label", label)
  dW1, dW2 = backward(label, input, y_hat, Z3, Z12_, Z12, W2)
  W1 -= dW1
  W2 -= dW2.reshape(1, 3)
  #print(dW1)
  #print(dW2.reshape(1, 3))
  #print("Q5 W1\n", W1)
  #print("Q5 W2\n", W2)

import numpy as np
def tanh(x) :
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

tanh(-0.7908)